on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
name: Update bucket
jobs:
  comments:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: |
          iwr -useb get.scoop.sh | iex
          scoop install hub
          ./bin/auto-pr.ps1 -p
